export function TermsOfService() {
  return (
    <div className="container mx-auto py-24">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold mb-8 text-white">Terms of Service</h1>

        <div className="prose prose-neutral dark:prose-invert text-white">
          <p>
            Welcome to <strong>AIVOLVE</strong>, a technology-based SaaS company specializing in NLP chatbots, Backdrop AI, generative AI tools, and other innovative AI solutions. By accessing or using our services, you agree to be bound by these Terms of Service ("Terms"). If you do not agree with these Terms, you may not access or use our services.
          </p>
<br />
          <strong><h2>1. Definitions</h2></strong>
          <ul>
            <li>
              <strong>1.1 "AIVOLVE":</strong> Refers to the company providing AI-powered tools, including NLP chatbots, Backdrop AI, and generative AI solutions.
            </li>
            <li>
              <strong>1.2 "Services":</strong> Include all software, platforms, tools, APIs, and support provided by AIVOLVE.
            </li>
            <li>
              <strong>1.3 "User":</strong> Refers to any individual or entity accessing or using AIVOLVE’s services.
            </li>
            <li>
              <strong>1.4 "Content":</strong> Refers to text, images, data, or other information generated, uploaded, or shared using our services.
            </li>
          </ul>
<br />
          <h2><strong>2. Acceptance of Terms</strong></h2>
          <ul>
            <li>
              <strong>2.1:</strong> By accessing or using our services, you agree to these Terms, our Privacy Policy, and any additional terms applicable to specific services.
            </li>
            <li>
              <strong>2.2:</strong> If you are using the services on behalf of an organization, you represent and warrant that you have the authority to bind the organization to these Terms.
            </li>
          </ul>
<br />
          <h2><strong>3. Use of Services</strong></h2>
          <ul>
            <li>
              <strong>3.1 Eligibility:</strong> You must be at least 18 years old or the legal age in your jurisdiction to use our services.
            </li>
            <li>
              <strong>3.2 Account Registration:</strong> To access certain services, you may need to create an account. You are responsible for safeguarding your account credentials and for all activities under your account.
            </li>
            <li>
              <strong>3.3 Permitted Use:</strong> You may only use the services in compliance with applicable laws and these Terms.
            </li>
            <li>
              <strong>3.4 Prohibited Use:</strong> You agree not to:
              <ul>
                <li>Use the services for illegal, harmful, or unethical purposes.</li>
                <li>Reverse-engineer, modify, or exploit our services without authorization.</li>
                <li>Submit content that infringes on third-party intellectual property rights or violates applicable laws.</li>
                <li>Use the services in a manner that disrupts, damages, or interferes with our systems.</li>
              </ul>
            </li>
          </ul>
<br />
          <h2><strong>4. Ownership and Licensing</strong></h2>
          <ul>
            <li>
              <strong>4.1 Ownership of Services:</strong> AIVOLVE retains all rights, title, and interest in and to the services, including any underlying software, features, or tools.
            </li>
            <li>
              <strong>4.2 User Content:</strong> You retain ownership of the content you create or upload while using the services. By submitting content, you grant AIVOLVE a non-exclusive, worldwide, royalty-free license to use, store, and process it solely to provide and improve the services.
            </li>
            <li>
              <strong>4.3 Generated Content:</strong> Any content generated by our AI tools is provided "as is," and you are responsible for ensuring compliance with applicable laws and regulations regarding its use.
            </li>
          </ul>
<br />
          <h2><strong>5. Fees and Payment</strong></h2>
          <ul>
            <li>
              <strong>5.1 Subscription Plans:</strong> Certain services may require payment or subscription. Pricing details are provided on our website or platform.
            </li>
            <li>
              <strong>5.2 Refunds:</strong> All payments are non-refundable unless explicitly stated otherwise in writing.
            </li>
            <li>
              <strong>5.3 Taxes:</strong> Users are responsible for any applicable taxes, fees, or duties related to the purchase of services.
            </li>
          </ul>
<br />
          <h2><strong>6. Privacy and Data Security</strong></h2>
          <p>
            Your use of our services is subject to our <strong>Privacy Policy</strong>, which explains how we collect, use, and protect your data. While we take reasonable measures to protect your data, you acknowledge that no system is completely secure, and AIVOLVE is not liable for unauthorized access to your data resulting from factors beyond our control.
          </p>
<br />
          <h2><strong>7. Service Availability and Updates</strong></h2>
          <p>
            While we strive for uninterrupted service, we do not guarantee 100% uptime. Downtime may occur due to maintenance, updates, or technical issues. AIVOLVE reserves the right to modify or discontinue any part of the services with prior notice where possible.
          </p>
<br />
          <h2><strong>8. Limitations of Liability</strong></h2>
          <ul>
            <li>
              <strong>8.1 Disclaimer:</strong> The services are provided "as is" without warranties of any kind, express or implied.
            </li>
            <li>
              <strong>8.2 Limitation:</strong> To the fullest extent permitted by law, AIVOLVE shall not be liable for any indirect, incidental, special, or consequential damages, including loss of data, revenue, or business.
            </li>
            <li>
              <strong>8.3 Maximum Liability:</strong> AIVOLVE’s total liability for any claim arising from or relating to the services is limited to the amount paid by you for the services in the 12 months preceding the claim.
            </li>
          </ul>
<br />
          <h2><strong>9. Indemnification</strong></h2>
          <p>
            You agree to indemnify, defend, and hold harmless AIVOLVE and its affiliates from and against any claims, liabilities, damages, losses, or expenses arising from your use of the services, violation of these Terms, or infringement of third-party rights.
          </p>
<br />
          <h2><strong>10. Termination</strong></h2>
          <p>
            You may terminate your account at any time by discontinuing use of the services. AIVOLVE reserves the right to suspend or terminate accounts for violation of these Terms or other prohibited activities.
          </p>
<br />
          <h2><strong>11. Governing Law and Dispute Resolution</strong></h2>
          <p>
            These Terms are governed by the laws of [Insert Jurisdiction]. Any disputes arising from these Terms shall be resolved through binding arbitration or in the courts of [Insert Jurisdiction].
          </p>
<br />
          <h2><strong>12. Miscellaneous</strong></h2>
          <ul>
            <li><strong>12.1 Entire Agreement:</strong> These Terms constitute the entire agreement between you and AIVOLVE.</li>
            <li><strong>12.2 Severability:</strong> If any provision of these Terms is found to be unenforceable, the remaining provisions remain in full force and effect.</li>
            <li><strong>12.3 No Waiver:</strong> Failure to enforce any provision does not constitute a waiver of rights under these Terms.</li>
          </ul>
<br />
<br />
          <p>
            If you have any questions or concerns about these Terms, please contact us at <strong>tech.aivolve@gmail.com</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}
